# This .yaml file is used to make changes to the hyperparameters of the model
# without having to go into the training and evaluation notebooks.

model:
  input_dim: 14 # do not change, this value is the number of features
  hidden_dim_1: 512
  hidden_dim_2: 256
  dropout_rate: 0.5

training:
  epochs: 250
  batch_size: 32
  learning_rate: 0.0001

mc_dropout:
  n_passes: 100 # should not be changed

paths:
  processed_dir: src/data/processed
  models_dir: src/models
  model_filename: pit_strategy_net_4.pth
  config_name: config_4.yaml
  folder_name: test4
  results_name: results4.txt